"""empty message

Revision ID: 626e341b3534
Revises: 
Create Date: 2024-10-08 21:04:38.851001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626e341b3534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
